Feature: Migrate client to NextJs with TypeScript
sidsbrmnn/image-uploader-client pull request #8
Opened 2020-10-09 06:59 UTC by phanlyhuynh

2020-10-09 07:42 UTC, phanlyhuynh commented
If it's good, please adding the "hacktoberfest-accepted" label. Thanks!!!

2020-10-09 07:51 UTC, sidsbrmnn requested changes
Thanks for the contribution! There are a few changes needed here. Could you remove the react-scripts from dependencies as it's not needed in a Next project and also remove yarn.lock as I want to maintain it using package-lock.json. Once these changes are made, the PR is good to go.

2020-10-09 08:21 UTC, sidsbrmnn requested changes

2020-10-09 08:21 UTC, sidsbrmnn commented on package.json
> +    "react-scripts": "^3.4.3"
react-scripts are not needed.

2020-10-10 04:28 UTC, phanlyhuynh commented on package.json
> +    "react-scripts": "^3.4.3"
@sidsbrmnn it's done !!!

2020-10-10 04:30 UTC, phanlyhuynh commented
@sidsbrmnn Please check for me. Thanks !!!

2020-10-10 04:32 UTC, sidsbrmnn commented
Perfect! Thanks for contributing

2020-10-10 04:32 UTC, merged

2020-10-11 05:03 UTC, phanlyhuynh commented
@sidsbrmnn why were you add "invalid" label?

2020-10-18 12:54 UTC, sidsbrmnn commented
@phanlyhuynh the app crashed completely with wrong implementation of state management in functional components.